site_name: etogeek MkDocs demo
theme:
  name: material
site_url: https://example12.github.io/mkdocs-demo-site
site_author: Iskander
copyright: Iskander, V, 2024

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences